affinity: {}
applicationProdProperties:
  configmap:
    application-prod.properties: >
      server.port=2001

      symplified.email.template.path=templates/email/

      logging.config=logback.xml


      spring.jpa.hibernate.ddl-auto=none

      spring.datasource.url=jdbc:mysql://my-release-mysql-primary.default.svc.cluster.local:3306/symplified

      spring.datasource.username=root

      spring.datasource.password=kalsym@123

      spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


      spring.mail.host=smtpout.secureserver.net

      spring.mail.port=465 


      spring.mail.username=no-reply@symplified.biz

      spring.mail.password=K@lSYmSyMPl1fieD@9796






      spring.mail.properties.mail.smtp.auth=true

      spring.mail.properties.mail.smtp.socketFactory.port=465


      spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory


      spring.output.ansi.enabled=ALWAYS


      liveChat.sendMessage.URL=https://live.symplified.it/api/v1/chat.postMessage

      liveChat.token=kkJ4G-gEqu5nL-VY9YWBo25otESh_zlQu8ckpic49ne

      livechat.userid=JEdxZxgW4R5Z53xq2


      product-service.URL=https://api.symplified.it/product-service/v1/

      product-service.token=Bearer accessToken

      symplified.logo.path=https://symplified.it/store-assets/symplified-logo-small.png

      services.user-service.bulk_authorities.url =
      https://api.symplified.it/user-service/v1/authorities/bulk

      services.user-service.session_details =
      https://api.symplified.it/user-service/v1/sessions/details
  volumeMount:
    - mountPath: /home/docker/Software/application-prod.properties
      name: email-service-approd-vol
      subPath: application-prod.properties
  volumes:
    - configMap:
        name: email-service-approd-cm
      name: email-service-approd-vol
applicationProperties:
  configmap:
    application.properties: >
      # Default config (refrain from editting this config, please add in
      application-prod.properties below)

      spring.profiles.active=prod

      proj.name=email-service

      build.version=@project.version@
  volumeMount:
    - mountPath: /home/docker/Software/application.properties
      name: email-service-ap-vol
      subPath: application.properties
  volumes:
    - configMap:
        name: email-service-ap-cm
      name: email-service-ap-vol
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: kalsym/email-service
  tag: 3.0.16-SNAPSHOT
imagePullSecrets:
  - name: kalsym-docker-hub
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: ''
  enabled: true
  hosts:
    - host: api.symplified.it
      paths:
        - path: /email-service/v1(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.symplified.it
      secretName: secret-tls-it
logback:
  configmap:
    logback.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>

          <property name="LOGS" value="/home/docker/Software/logs/symplified" />
          <property name="CDRS" value="/home/docker/Software/logs" />

          <property resource="application.properties" />

          <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
              <layout class="ch.qos.logback.classic.PatternLayout">
                  <Pattern>
                      %black(%d{ISO8601}) %highlight(%-5level) %yellow(%C{1.}): %msg%n%throwable
                  </Pattern>
              </layout>
          </appender>

          <appender name="APPLICATION" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <file>${LOGS}/email-service/email-service.log</file>
              <append>true</append>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <!-- rollover daily and when the file reaches 10 MegaBytes -->
                  <fileNamePattern>${LOGS}/email-service/archived/email-service-%d{yyyy-MM-dd}.%i.log
                  </fileNamePattern>
                  <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                      <maxFileSize>10MB</maxFileSize>
                  </timeBasedFileNamingAndTriggeringPolicy>
              </rollingPolicy>
              <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                  <charset>UTF-8</charset>
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <Pattern>%d %p %M %L [%t] - %m%n</Pattern>
                  </layout>
              </encoder>
          </appender>

          <appender name="CDR" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <file>${CDRS}/email-service-cdr.csv</file>
              <append>true</append>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <!-- rollover daily and when the file reaches 10 MegaBytes -->
                  <fileNamePattern>${CDRS}/email-service/cdrs/cdr-%d{yyyy-MM-dd}.%i.csv
                  </fileNamePattern>
                  <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                      <maxFileSize>10MB</maxFileSize>
                  </timeBasedFileNamingAndTriggeringPolicy>
              </rollingPolicy>
              <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                  <charset>UTF-8</charset>
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <Pattern>%date{dd:MMM:yyyy;HH:mm:ss.SSS},%m%n</Pattern>
                  </layout>
              </encoder>
          </appender>

          <!-- LOG everything at INFO level -->
          <root level="INFO">
              <appender-ref ref="APPLICATION" />
          </root>

          <logger name="cdr" level="DEBUG" additivity="false">
              <appender-ref ref="CDR" />
          </logger>

          <!-- LOG "com.baeldung*" at TRACE level -->
          <!-- <logger name="application" level="DEBUG" additivity="true">
              <appender-ref ref="APPLICATION" />
          </logger> -->

      </configuration>
  volumeMount:
    - mountPath: /home/docker/Software/logback.xml
      name: email-service-lgb-vol
      subPath: logback.xml
  volumes:
    - configMap:
        name: email-service-lgb-cm
      name: email-service-lgb-vol
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 2001
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []